---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: centos/postgresql-12-centos7
    ports:
      - "5432:5432"
    environment:
      - PGDATA=postgres
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=db_order
    networks:
      - kafka-network

  order_app:
    image: order_app:0.1
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres
    networks:
      - kafka-network


networks:
  kafka-network:
    name: kafka-network
